# Generated by Django 4.1.7 on 2023-02-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citybase",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
        migrations.CreateModel(
            name="TempBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp", models.IntegerField(verbose_name="Температура")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "i_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.citybase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение температуры",
                "verbose_name_plural": "Значения температур",
            },
        ),
    ]
