# Generated by Django 4.1.7 on 2023-02-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_citybase_options_tempbase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempbase",
            name="i_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="database.citybase",
                verbose_name="Город",
            ),
        ),
    ]
