# Generated by Django 4.1.7 on 2023-02-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_temperaturebase"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureBaseOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperaturedata", models.IntegerField(verbose_name="Температура")),
                ("date", models.DateField(verbose_name="Дата")),
                ("t", models.TimeField(verbose_name="Час")),
                (
                    "i_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.citybase",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение температуры",
                "verbose_name_plural": "Значения температур",
            },
        ),
    ]
