# Generated by Django 4.1.7 on 2023-02-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_temperaturebaseon"),
    ]

    operations = [
        migrations.RemoveField(model_name="temperaturebase", name="i_city",),
        migrations.DeleteModel(name="TempBase",),
        migrations.DeleteModel(name="TemperatureBase",),
    ]
